// Statisk spilleliste for "Slot Wheel"-funksjonen på forsiden. Legg til flere spill her etter
// hvert -- rekkefølgen spiller ingen rolle, spinnet velger tilfeldig blant alle.

export interface WheelGame {
  id: string
  name: string
  provider: string
  /** Portrett cover art (public/wheel/). */
  image: string
  /**
   * De fleste bildene er hentet direkte fra Hype.bet sin egen
   * custom-game-miniatures-CDN (hype.bet/s3/custom-game-miniatures/{leverandørkode}_{spillnavn}.webp)
   * og har allerede tittel + leverandør pent innebygd i bildet. Et fåtall spill sin eksakte
   * URL på den CDN-en er ikke funnet ennå -- for de bruker vi et beskåret utsnitt uten
   * innebygd tekst, og setter needsLabel:true for å vise tittel/leverandør som overlay i UI-et.
   */
  needsLabel?: boolean
}

export const WHEEL_GAMES: WheelGame[] = [
  { id: 'wanted', name: 'Wanted Dead or a Wild', provider: 'Hacksaw Gaming', image: '/wheel/wanted.jpg' },
  { id: 'banana-farm', name: 'Banana Farm', provider: 'Hacksaw Gaming', image: '/wheel/banana-farm.jpg' },
  { id: 'le-bandit', name: 'Le Bandit', provider: 'Hacksaw Gaming', image: '/wheel/le-bandit.jpg' },
  { id: 'shogun', name: 'Shogun Skylord: Jade Empress', provider: 'Just Slots', image: '/wheel/shogun.jpg' },
  { id: 'mental2', name: 'Mental 2', provider: 'Nolimit City', image: '/wheel/mental2.jpg' },
  { id: 'frkn-bananas', name: 'FRKN Bananas', provider: 'Hacksaw Gaming', image: '/wheel/frkn-bananas.jpg' },
  { id: 'fist', name: 'Fist of Destruction', provider: 'Hacksaw Gaming', image: '/wheel/fist.jpg' },
  { id: 'ripcity', name: 'RIP City', provider: 'Hacksaw Gaming', image: '/wheel/ripcity.jpg' },
  { id: 'anubis', name: 'Hand of Anubis', provider: 'Hacksaw Gaming', image: '/wheel/anubis.jpg' },
  { id: 'dorkunit', name: 'Dork Unit', provider: 'Hacksaw Gaming', image: '/wheel/dorkunit.jpg' },
  { id: 'jawsofjustice', name: 'Jaws of Justice', provider: 'Hacksaw Gaming', image: '/wheel/jawsofjustice.jpg' },
  { id: 'lifeanddeath', name: 'Life and Death', provider: 'Hacksaw Gaming', image: '/wheel/lifeanddeath.jpg' },
  { id: 'duckhuntershh', name: 'Duck Hunters: Happy Hour', provider: 'Nolimit City', image: '/wheel/duckhuntershh.jpg' },
  { id: 'juicyfruits', name: 'Juicy Fruits', provider: 'Pragmatic Play', image: '/wheel/juicyfruits.jpg' },
  { id: 'sunprincess', name: 'Sun Princess', provider: 'Hacksaw Gaming', image: '/wheel/sunprincess.jpg' },
  { id: 'bookofpower', name: 'Book of Power', provider: 'Relax Gaming', image: '/wheel/bookofpower.jpg' },
  { id: 'armyofares', name: 'Army of Ares', provider: 'Hacksaw Gaming', image: '/wheel/armyofares.jpg' },
  { id: 'crazyexgf', name: "Crazy Ex-Girlfriend", provider: 'Nolimit City', image: '/wheel/crazyexgf.jpg' },
  { id: 'seamen', name: 'Seamen', provider: 'Nolimit City', image: '/wheel/seamen.jpg' },
  { id: 'mayanstackways', name: 'Mayan Stackways', provider: 'Hacksaw Gaming', image: '/wheel/mayanstackways.jpg' },
  { id: 'rainandruin', name: 'Rain and Ruin', provider: 'Just Slots', image: '/wheel/rainandruin.jpg' },
  { id: 'demonsgate', name: "Demon's Gate", provider: 'Slotmill', image: '/wheel/demonsgate.jpg' },
  { id: 'duckhunters', name: 'Duck Hunters', provider: 'Nolimit City', image: '/wheel/duckhunters.jpg' },
  { id: 'zeusvshades', name: 'Zeus vs Hades: Gods of War', provider: 'Pragmatic Play', image: '/wheel/zeusvshades.jpg' },
  { id: 'leking', name: 'Le King', provider: 'Hacksaw Gaming', image: '/wheel/leking.jpg' },
  { id: 'flightmode', name: 'Flight Mode', provider: 'Nolimit City', image: '/wheel/flightmode.jpg' },
  { id: 'le-prechaun', name: 'Le Prechaun', provider: 'Hacksaw Gaming', image: '/wheel/leprechaun.jpg' },
  { id: 'houndsofhell', name: 'Hounds of Hell', provider: 'Hacksaw Gaming', image: '/wheel/houndsofhell.jpg' },
  { id: 'outsourced', name: 'Outsourced', provider: 'Nolimit City', image: '/wheel/outsourced.jpg' },
  { id: 'crystalrobot', name: 'Crystal Robot', provider: 'Backseat Gaming', image: '/wheel/crystalrobot.jpg' },
  { id: 'jellyexpress', name: 'Jelly Express', provider: 'Pragmatic Play', image: '/wheel/jellyexpress.jpg' },
  { id: 'wildwoodcurse', name: 'The Wildwood Curse', provider: 'Hacksaw Gaming', image: '/wheel/wildwoodcurse.jpg' },
  { id: 'doghouse1000', name: 'The Dog House Megaways 1000', provider: 'Pragmatic Play', image: '/wheel/doghouse1000.jpg' },
  { id: 'chocolaterocket', name: 'Chocolate Rocket', provider: 'Hacksaw Gaming', image: '/wheel/chocolaterocket.jpg' },
  { id: 'fighterpit', name: 'Fighter Pit', provider: 'Hacksaw Gaming', image: '/wheel/fighterpit.jpg' },
  { id: 'soakedbyseamen', name: 'Soaked by Seamen', provider: 'Nolimit City', image: '/wheel/soakedbyseamen.jpg' },
  { id: 'puglife', name: 'Pug Life', provider: 'Hacksaw Gaming', image: '/wheel/puglife.jpg' },
  { id: '2wild2die', name: '2 Wild 2 Die', provider: 'Hacksaw Gaming', image: '/wheel/2wild2die.jpg' },
  { id: 'dasxbootzwei', name: 'Das xBoot Zwei', provider: 'Nolimit City', image: '/wheel/dasxboot2wei.jpg' },
  { id: 'goldenshower', name: 'Golden Shower', provider: 'Nolimit City', image: '/wheel/goldenshower.jpg' },
  { id: 'aztecmagicmegaways', name: 'Aztec Magic Megaways', provider: 'BGaming', image: '/wheel/aztecmagicmegaways.jpg' },
  { id: 'piratebonanza2', name: 'Pirate Bonanza 2', provider: 'Backseat Gaming', image: '/wheel/piratebonanza2.jpg' },
  { id: 'chaoscrewii', name: 'Chaos Crew II', provider: 'Hacksaw Gaming', image: '/wheel/chaoscrewii.jpg', needsLabel: true },
  { id: 'wildwestduels', name: 'Wild West Duels', provider: 'Pragmatic Play', image: '/wheel/wildwestduels.jpg' },
  { id: 'angelvssinner', name: 'Angel vs Sinner', provider: 'Pragmatic Play', image: '/wheel/angelvssinner.jpg' },
  { id: 'reelrampage', name: 'Reel Rampage', provider: 'Slotmill', image: '/wheel/reelrampage.jpg' },
  { id: 'duckhunters2', name: 'Duck Hunters 2', provider: 'Nolimit City', image: '/wheel/duckhunters2.jpg' },
  { id: 'nitronights', name: 'Nitro Nights', provider: 'Hacksaw Gaming', image: '/wheel/nitronights.jpg' },
  { id: 'roninstackways', name: 'Ronin Stackways', provider: 'Hacksaw Gaming', image: '/wheel/roninstackways.jpg' },
  { id: 'ultimateslotofamerica', name: 'Ultimate Slot of America', provider: 'Hacksaw Gaming', image: '/wheel/ultimateslotofamerica.jpg' },
  { id: 'bruteforcealienonslaught', name: 'Brute Force: Alien Onslaught', provider: 'Nolimit City', image: '/wheel/bruteforcealienonslaught.jpg' },
  { id: 'bizarre', name: 'Bizarre', provider: 'Nolimit City', image: '/wheel/bizarre.jpg' },
  { id: 'itero', name: 'Itero', provider: 'Hacksaw Gaming', image: '/wheel/itero.jpg' },
  { id: 'disorder', name: 'Disorder', provider: 'Nolimit City', image: '/wheel/disorder.jpg' },
  { id: 'spearofathena', name: 'Spear of Athena', provider: 'Hacksaw Gaming', image: '/wheel/spearofathena.jpg' },
  { id: 'shogunskylord1', name: 'Shogun Skylord', provider: 'Just Slots', image: '/wheel/shogunskylord1.jpg' },
  { id: 'piratebonanza', name: 'Pirate Bonanza', provider: 'Hacksaw Gaming', image: '/wheel/piratebonanza.jpg' },
  { id: 'bigbamboo2', name: 'Big Bamboo II', provider: 'Push Gaming', image: '/wheel/bigbamboo2.jpg' },
  { id: 'breakout', name: 'Breakout', provider: 'Nolimit City', image: '/wheel/breakout.jpg' },
  { id: 'bookofshadows', name: 'Book of Shadows', provider: 'Nolimit City', image: '/wheel/bookofshadows.jpg' },
  { id: 'beastgains', name: 'Beast Gains', provider: 'Relax Gaming', image: '/wheel/beastgains.jpg' },
  { id: 'holyhandgrenade2', name: 'Holy Hand Grenade II', provider: 'Relax Gaming', image: '/wheel/holyhandgrenade2.jpg' },
  { id: 'xwayshoarder2', name: 'xWays Hoarder 2', provider: 'Nolimit City', image: '/wheel/xwayshoarder2.jpg' },
  { id: 'folsomprison', name: 'Folsom Prison', provider: 'Nolimit City', image: '/wheel/folsomprison.jpg' },
  { id: 'dasxboot', name: 'Das xBoot', provider: 'Nolimit City', image: '/wheel/dasxboot.jpg' },
  { id: 'lepharaoh', name: 'Le Pharaoh', provider: 'Hacksaw Gaming', image: '/wheel/lepharaoh.jpg' },
  { id: 'netgains', name: 'Net Gains', provider: 'Relax Gaming', image: '/wheel/netgains.jpg' },
  { id: 'sixsixsix', name: '666', provider: 'Hacksaw Gaming', image: '/wheel/sixsixsix.jpg' },
  { id: 'bigbassfootballbonanza', name: 'Big Bass Football Bonanza', provider: 'Pragmatic Play', image: '/wheel/bigbassfootballbonanza.jpg' },
  { id: 'ravsosiris', name: 'Ra vs Osiris', provider: 'Pragmatic Play', image: '/wheel/ravsosiris.jpg' },
  { id: 'darksummoning', name: 'Dark Summoning', provider: 'Hacksaw Gaming', image: '/wheel/darksummoning.jpg' },
  { id: 'deadmansdrop', name: "Dead Man's Drop", provider: 'Slotmill', image: '/wheel/deadmansdrop.jpg' },
  { id: 'sugarrush1000', name: 'Sugar Rush 1000', provider: 'Pragmatic Play', image: '/wheel/sugarrush1000.jpg' },
  { id: 'xmasdrop', name: 'Xmas Drop', provider: 'Hacksaw Gaming', image: '/wheel/xmasdrop.jpg' },
  { id: 'fishmafia', name: 'Fish Mafia', provider: 'Just Slots', image: '/wheel/fishmafia.jpg' },
  { id: 'bonanzatrillion', name: 'Bonanza Trillion', provider: 'BGaming', image: '/wheel/bonanzatrillion.jpg' },
  { id: 'digdigdigger', name: 'Dig Dig Digger', provider: 'BGaming', image: '/wheel/digdigdigger.jpg' },
  { id: 'luckypennypowerscatter', name: 'Lucky Penny Power Scatter', provider: '3 Oaks Gaming', image: '/wheel/luckypennypowerscatter.jpg' },
  { id: 'luckyapplex1000', name: 'Lucky Apple x1000', provider: '3 Oaks Gaming', image: '/wheel/luckyapplex1000.jpg' },
  { id: 'djtigerx1000', name: 'DJ Tiger x1000', provider: '3 Oaks Gaming', image: '/wheel/djtigerx1000.jpg' },
  { id: 'ultrafruitsmash', name: 'Ultra Fruit Smash', provider: 'Slotmill', image: '/wheel/ultrafruitsmash.jpg' },
  { id: 'emberfall', name: 'Emberfall', provider: 'Slotmill', image: '/wheel/emberfall.jpg' },
  { id: 'goldenscrolls', name: 'Golden Scrolls', provider: 'Slotmill', image: '/wheel/goldenscrolls.jpg' },
  { id: 'ironbank2', name: 'Iron Bank 2', provider: 'Relax Gaming', image: '/wheel/ironbank2.jpg' },
  { id: 'moneytrain3', name: 'Money Train 3', provider: 'Relax Gaming', image: '/wheel/moneytrain3.jpg' },
  { id: 'moneytrain4', name: 'Money Train 4', provider: 'Relax Gaming', image: '/wheel/moneytrain4.jpg' },
  { id: 'bigbamboo', name: 'Big Bamboo', provider: 'Push Gaming', image: '/wheel/bigbamboo.jpg' },
  { id: 'fatbanker', name: 'Fat Banker', provider: 'Push Gaming', image: '/wheel/fatbanker.jpg' },
  { id: 'razorreturns', name: 'Razor Returns', provider: 'Push Gaming', image: '/wheel/razorreturns.jpg' },
  { id: 'starlightprincesssuperscatter', name: 'Starlight Princess Super Scatter', provider: 'Pragmatic Play', image: '/wheel/starlightprincesssuperscatter.jpg' },
  { id: 'biggerbarnhousebonanza', name: 'Bigger Barn House Bonanza', provider: 'Pragmatic Play', image: '/wheel/biggerbarnhousebonanza.jpg' },
  { id: 'sugarrushsuperscatter', name: 'Sugar Rush Super Scatter', provider: 'Pragmatic Play', image: '/wheel/sugarrushsuperscatter.jpg' },
  { id: 'vampyparty', name: 'Vampy Party', provider: 'Pragmatic Play', image: '/wheel/vampyparty.jpg' },
  { id: 'jadelegends', name: 'Jade Legends', provider: 'Pragmatic Play', image: '/wheel/jadelegends.jpg' },
  { id: 'bruteforce', name: 'Brute Force', provider: 'Nolimit City', image: '/wheel/bruteforce.jpg' },
  { id: 'outsourced2', name: 'Outsourced 2', provider: 'Nolimit City', image: '/wheel/outsourced2.jpg' },
  { id: 'darkforge', name: 'Dark Forge', provider: 'Slotmill', image: '/wheel/darkforge.jpg' },
  { id: 'deadmanstrail', name: "Dead Man's Trail", provider: 'Relax Gaming', image: '/wheel/deadmanstrail.jpg' },
  { id: 'bookofabyss', name: 'Book of Abyss', provider: 'Just Slots', image: '/wheel/bookofabyss.jpg' },
  { id: 'immortal5', name: 'Immortal 5', provider: 'Relax Gaming', image: '/wheel/immortal5.jpg' },
  { id: 'fistofdestructionmegamultiplier', name: 'Fist of Destruction Megamultiplier', provider: 'Hacksaw Gaming', image: '/wheel/fistofdestructionmegamultiplier.jpg' },
  { id: 'sweetbonanza2500', name: 'Sweet Bonanza 2500', provider: 'Pragmatic Play', image: '/wheel/sweetbonanza2500.jpg' },
  { id: '5lionsmegaways2', name: '5 Lions Megaways 2', provider: 'Pragmatic Play', image: '/wheel/5lionsmegaways2.jpg' },
  { id: 'zombieschoolmegaways', name: 'Zombie School Megaways', provider: 'Pragmatic Play', image: '/wheel/zombieschoolmegaways.jpg' },
  { id: 'retroverse', name: 'Retroverse', provider: 'Push Gaming', image: '/wheel/retroverse.jpg' },
  { id: 'seaofspirits', name: 'Sea of Spirits', provider: 'Push Gaming', image: '/wheel/seaofspirits.jpg' },
]

/** Alle spill spilles under vårt Hype.bet-partnerlink -- ingen per-spill dyplenke tilgjengelig. */
export const HYPE_PLAY_URL = 'https://hype.bet/LuckAndLoad'
